### ISSUE TITLE
get without splay

### ISSUE THREAD

**Issue by mpetri** [sile/splay_tree#3]
is it possible to implement `get` without splay in the case I have a `&self` only?

**Comment by mpetri** [comment]
some more context. Let's say I want to have the ability to only splay when I modify the map with `get_mut()` or if I have a read-only copy of another splay tree that I want to look up some values from and insert into the new splay tree.

**Comment by sile** [comment]
Technically, it's possible to add the `&self` version of `get`. However, as splay tree is an amortized data structure, it could greatly degrade the performance (`get(&mut self, ..)` ensures that it only takes `O(log N)` amortized cost, but `get(&self, ..)` will take `O(N)`  in the worst case).
So it might be better to use other data structures if you need immutable look-up operations I think.

**Comment by mpetri** [comment]
I understand the contention. In my use case ([left_right](https://docs.rs/left-right/latest/left_right/)) I have two splay trees that I synchronize and requiring a mutable reference for the second one is problematic given that it is in read-only mode at the time. given that splay trees should just be able to walk the tree without splaying in special cases such as this I thought it would be a viable request.

**Comment by sile** [comment]
Thank you for your additional information. I will see the link and consider to implement the read only look up in this crate when I have time (maybe this weekend).

**Comment by sile** [comment]
I just added lookup methods without splay and published the new version [v0.3.1](https://crates.io/crates/splay_tree/0.3.1).

Thank you for your useful feedback.

**Comment by mpetri** [comment]
Thanks for taking the time to work on this request. Very helpful and working as intended!
